import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { css, styled } from '@stitches/react';
import type * as Stitches from '@stitches/react';

// import { Inter } from 'next/font/google'
import HeaderMenu from '@/components/HeaderMenu'

// const inter = Inter({ subsets: ['latin'] })

const headerStyle = 'text-3xl, font-bold'


const Main = styled("main", {
  
});

export default function Home() {
  return (
    <>
      <Head>
        <title>LoLFans</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderMenu />

      <div css={{
        "display": "flex",
        "flex-direction": "column",
        "justify-content": "space-between",
        "align-items": "center",
        "padding": "6rem",
        "min-height": "100vh",
      }}>
        <h1 tw={headerStyle}>LoLfans</h1>
      </div>
    </>
  )
}
